// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdnJ6MwMj7izEqeqnx3q0AfDOg2mIyfqU',
    appId: '1:176827234681:web:7138eb6d8335b2f46d17a8',
    messagingSenderId: '176827234681',
    projectId: 'notes-application-2791c',
    authDomain: 'notes-application-2791c.firebaseapp.com',
    storageBucket: 'notes-application-2791c.firebasestorage.app',
    measurementId: 'G-JHD0VB8GVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Zw9U67n_1hozkT3RXtXe7T1kIBsqx8c',
    appId: '1:176827234681:android:edef59b1ace1fa3e6d17a8',
    messagingSenderId: '176827234681',
    projectId: 'notes-application-2791c',
    storageBucket: 'notes-application-2791c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvWFXxIGwSP6qS_jJGBRobCsocpMZKt90',
    appId: '1:176827234681:ios:6bcb0afefd5a74826d17a8',
    messagingSenderId: '176827234681',
    projectId: 'notes-application-2791c',
    storageBucket: 'notes-application-2791c.firebasestorage.app',
    iosBundleId: 'com.example.notesApplication',
  );
}
